os:
  - linux

language: php

php:
  - '7.1'

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --force
  - cp .env.travis .env.testing

script:
  - vendor/bin/phpunit
