os:
  - linux

language: php

php:
  - '7.1'

language: node_js
node_js:
  - "6"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - cp .env.travis .env.testing
  - php artisan migrate --force
  - npm install
  - npm run test

script:
  - vendor/bin/phpunit
